// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rpcdemo/rpcdemo.proto

package rpcdemo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRpcDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRpcDemoRequest) Reset() {
	*x = CreateRpcDemoRequest{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRpcDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRpcDemoRequest) ProtoMessage() {}

func (x *CreateRpcDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRpcDemoRequest.ProtoReflect.Descriptor instead.
func (*CreateRpcDemoRequest) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRpcDemoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRpcDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRpcDemoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateRpcDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRpcDemoReply) Reset() {
	*x = CreateRpcDemoReply{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRpcDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRpcDemoReply) ProtoMessage() {}

func (x *CreateRpcDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRpcDemoReply.ProtoReflect.Descriptor instead.
func (*CreateRpcDemoReply) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRpcDemoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteRpcDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRpcDemoRequest) Reset() {
	*x = DeleteRpcDemoRequest{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRpcDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRpcDemoRequest) ProtoMessage() {}

func (x *DeleteRpcDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRpcDemoRequest.ProtoReflect.Descriptor instead.
func (*DeleteRpcDemoRequest) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRpcDemoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteRpcDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRpcDemoReply) Reset() {
	*x = DeleteRpcDemoReply{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRpcDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRpcDemoReply) ProtoMessage() {}

func (x *DeleteRpcDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRpcDemoReply.ProtoReflect.Descriptor instead.
func (*DeleteRpcDemoReply) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRpcDemoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateRpcDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRpcDemoRequest) Reset() {
	*x = UpdateRpcDemoRequest{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRpcDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRpcDemoRequest) ProtoMessage() {}

func (x *UpdateRpcDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRpcDemoRequest.ProtoReflect.Descriptor instead.
func (*UpdateRpcDemoRequest) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRpcDemoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRpcDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateRpcDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRpcDemoReply) Reset() {
	*x = UpdateRpcDemoReply{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRpcDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRpcDemoReply) ProtoMessage() {}

func (x *UpdateRpcDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRpcDemoReply.ProtoReflect.Descriptor instead.
func (*UpdateRpcDemoReply) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRpcDemoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRpcDemoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SelectRpcDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRpcDemoRequest) Reset() {
	*x = SelectRpcDemoRequest{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRpcDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRpcDemoRequest) ProtoMessage() {}

func (x *SelectRpcDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRpcDemoRequest.ProtoReflect.Descriptor instead.
func (*SelectRpcDemoRequest) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{6}
}

func (x *SelectRpcDemoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SelectRpcDemoReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Demos         []*SelectRpcDemoReply_Item `protobuf:"bytes,1,rep,name=demos,proto3" json:"demos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRpcDemoReply) Reset() {
	*x = SelectRpcDemoReply{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRpcDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRpcDemoReply) ProtoMessage() {}

func (x *SelectRpcDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRpcDemoReply.ProtoReflect.Descriptor instead.
func (*SelectRpcDemoReply) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{7}
}

func (x *SelectRpcDemoReply) GetDemos() []*SelectRpcDemoReply_Item {
	if x != nil {
		return x.Demos
	}
	return nil
}

type SelectRpcDemoReply_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRpcDemoReply_Item) Reset() {
	*x = SelectRpcDemoReply_Item{}
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRpcDemoReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRpcDemoReply_Item) ProtoMessage() {}

func (x *SelectRpcDemoReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_rpcdemo_rpcdemo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRpcDemoReply_Item.ProtoReflect.Descriptor instead.
func (*SelectRpcDemoReply_Item) Descriptor() ([]byte, []int) {
	return file_rpcdemo_rpcdemo_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SelectRpcDemoReply_Item) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SelectRpcDemoReply_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelectRpcDemoReply_Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_rpcdemo_rpcdemo_proto protoreflect.FileDescriptor

const file_rpcdemo_rpcdemo_proto_rawDesc = "" +
	"\n" +
	"\x15rpcdemo/rpcdemo.proto\x12\vapi.rpcdemo\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"R\n" +
	"\x14CreateRpcDemoRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"(\n" +
	"\x12CreateRpcDemoReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"*\n" +
	"\x14DeleteRpcDemoRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"(\n" +
	"\x12DeleteRpcDemoReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\">\n" +
	"\x14UpdateRpcDemoRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\x12UpdateRpcDemoReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x14SelectRpcDemoRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\x94\x01\n" +
	"\x12SelectRpcDemoReply\x12:\n" +
	"\x05demos\x18\x01 \x03(\v2$.api.rpcdemo.SelectRpcDemoReply.ItemR\x05demos\x1aB\n" +
	"\x04Item\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type2\xf6\x03\n" +
	"\aRpcdemo\x12y\n" +
	"\rCreateRpcDemo\x12!.api.rpcdemo.CreateRpcDemoRequest\x1a\x1f.api.rpcdemo.CreateRpcDemoReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/demo/create-rpc-demo\x12}\n" +
	"\rDeleteRpcDemo\x12!.api.rpcdemo.DeleteRpcDemoRequest\x1a\x1f.api.rpcdemo.DeleteRpcDemoReply\"(\x82\xd3\xe4\x93\x02\"* /api/demo/create-rpc-demo/{code}\x12y\n" +
	"\rUpdateRpcDemo\x12!.api.rpcdemo.UpdateRpcDemoRequest\x1a\x1f.api.rpcdemo.UpdateRpcDemoReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/demo/update-rpc-demo\x12v\n" +
	"\rSelectRpcDemo\x12!.api.rpcdemo.SelectRpcDemoRequest\x1a\x1f.api.rpcdemo.SelectRpcDemoReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/demo/select-rpc-demoBP\n" +
	"\vapi.rpcdemoP\x01Z?github.com/orzkratos/demokratos/demo1kratos/api/rpcdemo;rpcdemob\x06proto3"

var (
	file_rpcdemo_rpcdemo_proto_rawDescOnce sync.Once
	file_rpcdemo_rpcdemo_proto_rawDescData []byte
)

func file_rpcdemo_rpcdemo_proto_rawDescGZIP() []byte {
	file_rpcdemo_rpcdemo_proto_rawDescOnce.Do(func() {
		file_rpcdemo_rpcdemo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcdemo_rpcdemo_proto_rawDesc), len(file_rpcdemo_rpcdemo_proto_rawDesc)))
	})
	return file_rpcdemo_rpcdemo_proto_rawDescData
}

var file_rpcdemo_rpcdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpcdemo_rpcdemo_proto_goTypes = []any{
	(*CreateRpcDemoRequest)(nil),    // 0: api.rpcdemo.CreateRpcDemoRequest
	(*CreateRpcDemoReply)(nil),      // 1: api.rpcdemo.CreateRpcDemoReply
	(*DeleteRpcDemoRequest)(nil),    // 2: api.rpcdemo.DeleteRpcDemoRequest
	(*DeleteRpcDemoReply)(nil),      // 3: api.rpcdemo.DeleteRpcDemoReply
	(*UpdateRpcDemoRequest)(nil),    // 4: api.rpcdemo.UpdateRpcDemoRequest
	(*UpdateRpcDemoReply)(nil),      // 5: api.rpcdemo.UpdateRpcDemoReply
	(*SelectRpcDemoRequest)(nil),    // 6: api.rpcdemo.SelectRpcDemoRequest
	(*SelectRpcDemoReply)(nil),      // 7: api.rpcdemo.SelectRpcDemoReply
	(*SelectRpcDemoReply_Item)(nil), // 8: api.rpcdemo.SelectRpcDemoReply.Item
}
var file_rpcdemo_rpcdemo_proto_depIdxs = []int32{
	8, // 0: api.rpcdemo.SelectRpcDemoReply.demos:type_name -> api.rpcdemo.SelectRpcDemoReply.Item
	0, // 1: api.rpcdemo.Rpcdemo.CreateRpcDemo:input_type -> api.rpcdemo.CreateRpcDemoRequest
	2, // 2: api.rpcdemo.Rpcdemo.DeleteRpcDemo:input_type -> api.rpcdemo.DeleteRpcDemoRequest
	4, // 3: api.rpcdemo.Rpcdemo.UpdateRpcDemo:input_type -> api.rpcdemo.UpdateRpcDemoRequest
	6, // 4: api.rpcdemo.Rpcdemo.SelectRpcDemo:input_type -> api.rpcdemo.SelectRpcDemoRequest
	1, // 5: api.rpcdemo.Rpcdemo.CreateRpcDemo:output_type -> api.rpcdemo.CreateRpcDemoReply
	3, // 6: api.rpcdemo.Rpcdemo.DeleteRpcDemo:output_type -> api.rpcdemo.DeleteRpcDemoReply
	5, // 7: api.rpcdemo.Rpcdemo.UpdateRpcDemo:output_type -> api.rpcdemo.UpdateRpcDemoReply
	7, // 8: api.rpcdemo.Rpcdemo.SelectRpcDemo:output_type -> api.rpcdemo.SelectRpcDemoReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpcdemo_rpcdemo_proto_init() }
func file_rpcdemo_rpcdemo_proto_init() {
	if File_rpcdemo_rpcdemo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcdemo_rpcdemo_proto_rawDesc), len(file_rpcdemo_rpcdemo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcdemo_rpcdemo_proto_goTypes,
		DependencyIndexes: file_rpcdemo_rpcdemo_proto_depIdxs,
		MessageInfos:      file_rpcdemo_rpcdemo_proto_msgTypes,
	}.Build()
	File_rpcdemo_rpcdemo_proto = out.File
	file_rpcdemo_rpcdemo_proto_goTypes = nil
	file_rpcdemo_rpcdemo_proto_depIdxs = nil
}
