// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rpcboom/rpcboom.proto

package rpcboom

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcboom_rpcboom_proto protoreflect.FileDescriptor

const file_rpcboom_rpcboom_proto_rawDesc = "" +
	"\n" +
	"\x15rpcboom/rpcboom.proto\x12\vapi.rpcboom\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto2\xcc\x03\n" +
	"\aRpcboom\x12X\n" +
	"\vBoomUnknown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/boom/unknown\x12[\n" +
	"\fBoomNotFound\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/boom/not-found\x12T\n" +
	"\tBoomVague\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/boom/vague\x12Y\n" +
	"\vBoomTxError\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/boom/tx-error\x12Y\n" +
	"\vBoomDbError\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/boom/db-errorBP\n" +
	"\vapi.rpcboomP\x01Z?github.com/orzkratos/demokratos/demo1kratos/api/rpcboom;rpcboomb\x06proto3"

var file_rpcboom_rpcboom_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_rpcboom_rpcboom_proto_depIdxs = []int32{
	0, // 0: api.rpcboom.Rpcboom.BoomUnknown:input_type -> google.protobuf.Empty
	0, // 1: api.rpcboom.Rpcboom.BoomNotFound:input_type -> google.protobuf.Empty
	0, // 2: api.rpcboom.Rpcboom.BoomVague:input_type -> google.protobuf.Empty
	0, // 3: api.rpcboom.Rpcboom.BoomTxError:input_type -> google.protobuf.Empty
	0, // 4: api.rpcboom.Rpcboom.BoomDbError:input_type -> google.protobuf.Empty
	0, // 5: api.rpcboom.Rpcboom.BoomUnknown:output_type -> google.protobuf.Empty
	0, // 6: api.rpcboom.Rpcboom.BoomNotFound:output_type -> google.protobuf.Empty
	0, // 7: api.rpcboom.Rpcboom.BoomVague:output_type -> google.protobuf.Empty
	0, // 8: api.rpcboom.Rpcboom.BoomTxError:output_type -> google.protobuf.Empty
	0, // 9: api.rpcboom.Rpcboom.BoomDbError:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcboom_rpcboom_proto_init() }
func file_rpcboom_rpcboom_proto_init() {
	if File_rpcboom_rpcboom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcboom_rpcboom_proto_rawDesc), len(file_rpcboom_rpcboom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcboom_rpcboom_proto_goTypes,
		DependencyIndexes: file_rpcboom_rpcboom_proto_depIdxs,
	}.Build()
	File_rpcboom_rpcboom_proto = out.File
	file_rpcboom_rpcboom_proto_goTypes = nil
	file_rpcboom_rpcboom_proto_depIdxs = nil
}
