// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.0
// source: rpcboom/rpcboom.proto

package rpcboom

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRpcboomBoomDbError = "/api.rpcboom.Rpcboom/BoomDbError"
const OperationRpcboomBoomNotFound = "/api.rpcboom.Rpcboom/BoomNotFound"
const OperationRpcboomBoomTxError = "/api.rpcboom.Rpcboom/BoomTxError"
const OperationRpcboomBoomUnknown = "/api.rpcboom.Rpcboom/BoomUnknown"
const OperationRpcboomBoomVague = "/api.rpcboom.Rpcboom/BoomVague"

type RpcboomHTTPServer interface {
	// BoomDbError BoomDbError returns DB_ERROR error (500)
	// BoomDbError 返回 DB_ERROR 错误 (500)
	BoomDbError(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomNotFound BoomNotFound returns USER_NOT_FOUND error (404)
	// BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
	BoomNotFound(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomTxError BoomTxError returns TX_ERROR error (500)
	// BoomTxError 返回 TX_ERROR 错误 (500)
	BoomTxError(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomUnknown BoomUnknown returns UNKNOWN error (500)
	// BoomUnknown 返回 UNKNOWN 错误 (500)
	BoomUnknown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomVague BoomVague returns GREETER_UNSPECIFIED error (500)
	// BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
	BoomVague(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

func RegisterRpcboomHTTPServer(s *http.Server, srv RpcboomHTTPServer) {
	r := s.Route("/")
	r.GET("/api/boom/unknown", _Rpcboom_BoomUnknown0_HTTP_Handler(srv))
	r.GET("/api/boom/not-found", _Rpcboom_BoomNotFound0_HTTP_Handler(srv))
	r.GET("/api/boom/vague", _Rpcboom_BoomVague0_HTTP_Handler(srv))
	r.GET("/api/boom/tx-error", _Rpcboom_BoomTxError0_HTTP_Handler(srv))
	r.GET("/api/boom/db-error", _Rpcboom_BoomDbError0_HTTP_Handler(srv))
}

func _Rpcboom_BoomUnknown0_HTTP_Handler(srv RpcboomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcboomBoomUnknown)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BoomUnknown(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Rpcboom_BoomNotFound0_HTTP_Handler(srv RpcboomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcboomBoomNotFound)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BoomNotFound(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Rpcboom_BoomVague0_HTTP_Handler(srv RpcboomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcboomBoomVague)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BoomVague(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Rpcboom_BoomTxError0_HTTP_Handler(srv RpcboomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcboomBoomTxError)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BoomTxError(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Rpcboom_BoomDbError0_HTTP_Handler(srv RpcboomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcboomBoomDbError)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BoomDbError(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type RpcboomHTTPClient interface {
	// BoomDbError BoomDbError returns DB_ERROR error (500)
	// BoomDbError 返回 DB_ERROR 错误 (500)
	BoomDbError(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// BoomNotFound BoomNotFound returns USER_NOT_FOUND error (404)
	// BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
	BoomNotFound(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// BoomTxError BoomTxError returns TX_ERROR error (500)
	// BoomTxError 返回 TX_ERROR 错误 (500)
	BoomTxError(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// BoomUnknown BoomUnknown returns UNKNOWN error (500)
	// BoomUnknown 返回 UNKNOWN 错误 (500)
	BoomUnknown(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// BoomVague BoomVague returns GREETER_UNSPECIFIED error (500)
	// BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
	BoomVague(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type RpcboomHTTPClientImpl struct {
	cc *http.Client
}

func NewRpcboomHTTPClient(client *http.Client) RpcboomHTTPClient {
	return &RpcboomHTTPClientImpl{client}
}

// BoomDbError BoomDbError returns DB_ERROR error (500)
// BoomDbError 返回 DB_ERROR 错误 (500)
func (c *RpcboomHTTPClientImpl) BoomDbError(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/boom/db-error"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcboomBoomDbError))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BoomNotFound BoomNotFound returns USER_NOT_FOUND error (404)
// BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
func (c *RpcboomHTTPClientImpl) BoomNotFound(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/boom/not-found"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcboomBoomNotFound))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BoomTxError BoomTxError returns TX_ERROR error (500)
// BoomTxError 返回 TX_ERROR 错误 (500)
func (c *RpcboomHTTPClientImpl) BoomTxError(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/boom/tx-error"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcboomBoomTxError))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BoomUnknown BoomUnknown returns UNKNOWN error (500)
// BoomUnknown 返回 UNKNOWN 错误 (500)
func (c *RpcboomHTTPClientImpl) BoomUnknown(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/boom/unknown"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcboomBoomUnknown))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BoomVague BoomVague returns GREETER_UNSPECIFIED error (500)
// BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
func (c *RpcboomHTTPClientImpl) BoomVague(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/boom/vague"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcboomBoomVague))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
