// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: rpcboom/rpcboom.proto

package rpcboom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpcboom_BoomUnknown_FullMethodName  = "/api.rpcboom.Rpcboom/BoomUnknown"
	Rpcboom_BoomNotFound_FullMethodName = "/api.rpcboom.Rpcboom/BoomNotFound"
	Rpcboom_BoomVague_FullMethodName    = "/api.rpcboom.Rpcboom/BoomVague"
	Rpcboom_BoomTxError_FullMethodName  = "/api.rpcboom.Rpcboom/BoomTxError"
	Rpcboom_BoomDbError_FullMethodName  = "/api.rpcboom.Rpcboom/BoomDbError"
)

// RpcboomClient is the client API for Rpcboom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Rpcboom service defines methods that return different error types
// Rpcboom 服务定义返回不同错误类型的方法
type RpcboomClient interface {
	// BoomUnknown returns UNKNOWN error (500)
	// BoomUnknown 返回 UNKNOWN 错误 (500)
	BoomUnknown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BoomNotFound returns USER_NOT_FOUND error (404)
	// BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
	BoomNotFound(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BoomVague returns GREETER_UNSPECIFIED error (500)
	// BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
	BoomVague(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BoomTxError returns TX_ERROR error (500)
	// BoomTxError 返回 TX_ERROR 错误 (500)
	BoomTxError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BoomDbError returns DB_ERROR error (500)
	// BoomDbError 返回 DB_ERROR 错误 (500)
	BoomDbError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type rpcboomClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcboomClient(cc grpc.ClientConnInterface) RpcboomClient {
	return &rpcboomClient{cc}
}

func (c *rpcboomClient) BoomUnknown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rpcboom_BoomUnknown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcboomClient) BoomNotFound(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rpcboom_BoomNotFound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcboomClient) BoomVague(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rpcboom_BoomVague_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcboomClient) BoomTxError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rpcboom_BoomTxError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcboomClient) BoomDbError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Rpcboom_BoomDbError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcboomServer is the server API for Rpcboom service.
// All implementations must embed UnimplementedRpcboomServer
// for forward compatibility.
//
// Rpcboom service defines methods that return different error types
// Rpcboom 服务定义返回不同错误类型的方法
type RpcboomServer interface {
	// BoomUnknown returns UNKNOWN error (500)
	// BoomUnknown 返回 UNKNOWN 错误 (500)
	BoomUnknown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomNotFound returns USER_NOT_FOUND error (404)
	// BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
	BoomNotFound(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomVague returns GREETER_UNSPECIFIED error (500)
	// BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
	BoomVague(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomTxError returns TX_ERROR error (500)
	// BoomTxError 返回 TX_ERROR 错误 (500)
	BoomTxError(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// BoomDbError returns DB_ERROR error (500)
	// BoomDbError 返回 DB_ERROR 错误 (500)
	BoomDbError(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedRpcboomServer()
}

// UnimplementedRpcboomServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcboomServer struct{}

func (UnimplementedRpcboomServer) BoomUnknown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoomUnknown not implemented")
}
func (UnimplementedRpcboomServer) BoomNotFound(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoomNotFound not implemented")
}
func (UnimplementedRpcboomServer) BoomVague(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoomVague not implemented")
}
func (UnimplementedRpcboomServer) BoomTxError(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoomTxError not implemented")
}
func (UnimplementedRpcboomServer) BoomDbError(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoomDbError not implemented")
}
func (UnimplementedRpcboomServer) mustEmbedUnimplementedRpcboomServer() {}
func (UnimplementedRpcboomServer) testEmbeddedByValue()                 {}

// UnsafeRpcboomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcboomServer will
// result in compilation errors.
type UnsafeRpcboomServer interface {
	mustEmbedUnimplementedRpcboomServer()
}

func RegisterRpcboomServer(s grpc.ServiceRegistrar, srv RpcboomServer) {
	// If the following call pancis, it indicates UnimplementedRpcboomServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpcboom_ServiceDesc, srv)
}

func _Rpcboom_BoomUnknown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcboomServer).BoomUnknown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcboom_BoomUnknown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcboomServer).BoomUnknown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcboom_BoomNotFound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcboomServer).BoomNotFound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcboom_BoomNotFound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcboomServer).BoomNotFound(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcboom_BoomVague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcboomServer).BoomVague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcboom_BoomVague_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcboomServer).BoomVague(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcboom_BoomTxError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcboomServer).BoomTxError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcboom_BoomTxError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcboomServer).BoomTxError(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpcboom_BoomDbError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcboomServer).BoomDbError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcboom_BoomDbError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcboomServer).BoomDbError(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpcboom_ServiceDesc is the grpc.ServiceDesc for Rpcboom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpcboom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rpcboom.Rpcboom",
	HandlerType: (*RpcboomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BoomUnknown",
			Handler:    _Rpcboom_BoomUnknown_Handler,
		},
		{
			MethodName: "BoomNotFound",
			Handler:    _Rpcboom_BoomNotFound_Handler,
		},
		{
			MethodName: "BoomVague",
			Handler:    _Rpcboom_BoomVague_Handler,
		},
		{
			MethodName: "BoomTxError",
			Handler:    _Rpcboom_BoomTxError_Handler,
		},
		{
			MethodName: "BoomDbError",
			Handler:    _Rpcboom_BoomDbError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcboom/rpcboom.proto",
}
