// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rpcping/rpcping.proto

package rpcping

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcping_rpcping_proto protoreflect.FileDescriptor

const file_rpcping_rpcping_proto_rawDesc = "" +
	"\n" +
	"\x15rpcping/rpcping.proto\x12\vapi.rpcping\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/wrappers.proto2h\n" +
	"\aRpcping\x12]\n" +
	"\x04Ping\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/service/pingBP\n" +
	"\vapi.rpcpingP\x01Z?github.com/orzkratos/demokratos/demo1kratos/api/rpcping;rpcpingb\x06proto3"

var file_rpcping_rpcping_proto_goTypes = []any{
	(*wrapperspb.StringValue)(nil), // 0: google.protobuf.StringValue
}
var file_rpcping_rpcping_proto_depIdxs = []int32{
	0, // 0: api.rpcping.Rpcping.Ping:input_type -> google.protobuf.StringValue
	0, // 1: api.rpcping.Rpcping.Ping:output_type -> google.protobuf.StringValue
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcping_rpcping_proto_init() }
func file_rpcping_rpcping_proto_init() {
	if File_rpcping_rpcping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcping_rpcping_proto_rawDesc), len(file_rpcping_rpcping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcping_rpcping_proto_goTypes,
		DependencyIndexes: file_rpcping_rpcping_proto_depIdxs,
	}.Build()
	File_rpcping_rpcping_proto = out.File
	file_rpcping_rpcping_proto_goTypes = nil
	file_rpcping_rpcping_proto_depIdxs = nil
}
