// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: rpcping/rpcping.proto

package rpcping

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpcping_Ping_FullMethodName = "/api.rpcping.Rpcping/Ping"
)

// RpcpingClient is the client API for Rpcping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcpingClient interface {
	Ping(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type rpcpingClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcpingClient(cc grpc.ClientConnInterface) RpcpingClient {
	return &rpcpingClient{cc}
}

func (c *rpcpingClient) Ping(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, Rpcping_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcpingServer is the server API for Rpcping service.
// All implementations must embed UnimplementedRpcpingServer
// for forward compatibility.
type RpcpingServer interface {
	Ping(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedRpcpingServer()
}

// UnimplementedRpcpingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcpingServer struct{}

func (UnimplementedRpcpingServer) Ping(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcpingServer) mustEmbedUnimplementedRpcpingServer() {}
func (UnimplementedRpcpingServer) testEmbeddedByValue()                 {}

// UnsafeRpcpingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcpingServer will
// result in compilation errors.
type UnsafeRpcpingServer interface {
	mustEmbedUnimplementedRpcpingServer()
}

func RegisterRpcpingServer(s grpc.ServiceRegistrar, srv RpcpingServer) {
	// If the following call pancis, it indicates UnimplementedRpcpingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpcping_ServiceDesc, srv)
}

func _Rpcping_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcpingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpcping_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcpingServer).Ping(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpcping_ServiceDesc is the grpc.ServiceDesc for Rpcping service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpcping_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rpcping.Rpcping",
	HandlerType: (*RpcpingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Rpcping_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcping/rpcping.proto",
}
