// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.0
// source: rpcping/rpcping.proto

package rpcping

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRpcpingPing = "/api.rpcping.Rpcping/Ping"

type RpcpingHTTPServer interface {
	Ping(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error)
}

func RegisterRpcpingHTTPServer(s *http.Server, srv RpcpingHTTPServer) {
	r := s.Route("/")
	r.GET("/api/service/ping", _Rpcping_Ping0_HTTP_Handler(srv))
}

func _Rpcping_Ping0_HTTP_Handler(srv RpcpingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.StringValue
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRpcpingPing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*wrapperspb.StringValue))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*wrapperspb.StringValue)
		return ctx.Result(200, reply)
	}
}

type RpcpingHTTPClient interface {
	Ping(ctx context.Context, req *wrapperspb.StringValue, opts ...http.CallOption) (rsp *wrapperspb.StringValue, err error)
}

type RpcpingHTTPClientImpl struct {
	cc *http.Client
}

func NewRpcpingHTTPClient(client *http.Client) RpcpingHTTPClient {
	return &RpcpingHTTPClientImpl{client}
}

func (c *RpcpingHTTPClientImpl) Ping(ctx context.Context, in *wrapperspb.StringValue, opts ...http.CallOption) (*wrapperspb.StringValue, error) {
	var out wrapperspb.StringValue
	pattern := "/api/service/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRpcpingPing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
