// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "helloworld/v1/error_reason.proto" (package "helloworld.v1", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum helloworld.v1.ErrorReason
 */
export enum ErrorReason {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: USER_NOT_FOUND = 40400;
     */
    USER_NOT_FOUND = 40400,
    /**
     * @generated from protobuf enum value: GREETER_UNSPECIFIED = 50000;
     */
    GREETER_UNSPECIFIED = 50000,
    /**
     * @generated from protobuf enum value: TX_ERROR = 50001;
     */
    TX_ERROR = 50001,
    /**
     * @generated from protobuf enum value: DB_ERROR = 50002;
     */
    DB_ERROR = 50002
}
