// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "rpcping/rpcping.proto" (package "api.rpcping", syntax proto3)
// tslint:disable
import { StringValue } from "../google/protobuf/wrappers";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service api.rpcping.Rpcping
 */
export const Rpcping = new ServiceType("api.rpcping.Rpcping", [
    { name: "Ping", options: { "google.api.http": { get: "/api/service/ping" } }, I: StringValue, O: StringValue }
]);
