// Code generated by protoc-gen-orzkratos-errors (errgenkratos). DO NOT EDIT.

package v1

import (
	errors "github.com/go-kratos/kratos/v2/errors"
	newerk "github.com/orzkratos/errkratos/newerk"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	return newerk.IsError(err, ErrorReason_UNKNOWN, 500)
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_UNKNOWN, format, args...)
}
func IsUserNotFound(err error) bool {
	return newerk.IsError(err, ErrorReason_USER_NOT_FOUND, 404)
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(404, ErrorReason_USER_NOT_FOUND, format, args...)
}
func IsGreeterUnspecified(err error) bool {
	return newerk.IsError(err, ErrorReason_GREETER_UNSPECIFIED, 500)
}

func ErrorGreeterUnspecified(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_GREETER_UNSPECIFIED, format, args...)
}
func IsTxError(err error) bool {
	return newerk.IsError(err, ErrorReason_TX_ERROR, 500)
}

func ErrorTxError(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_TX_ERROR, format, args...)
}
func IsDbError(err error) bool {
	return newerk.IsError(err, ErrorReason_DB_ERROR, 500)
}

func ErrorDbError(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_DB_ERROR, format, args...)
}
