// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "rpcboom/rpcboom.proto" (package "api.rpcboom", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service api.rpcboom.Rpcboom
 */
export const Rpcboom = new ServiceType("api.rpcboom.Rpcboom", [
    { name: "BoomUnknown", options: { "google.api.http": { get: "/api/boom/unknown" } }, I: Empty, O: Empty },
    { name: "BoomNotFound", options: { "google.api.http": { get: "/api/boom/not-found" } }, I: Empty, O: Empty },
    { name: "BoomVague", options: { "google.api.http": { get: "/api/boom/vague" } }, I: Empty, O: Empty },
    { name: "BoomTxError", options: { "google.api.http": { get: "/api/boom/tx-error" } }, I: Empty, O: Empty },
    { name: "BoomDbError", options: { "google.api.http": { get: "/api/boom/db-error" } }, I: Empty, O: Empty }
]);
