// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "rpcboom/rpcboom.proto" (package "api.rpcboom", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Rpcboom } from "./rpcboom";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Empty } from "../google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrtp } from '@yyle88/grpt/src/grpcviahttp';
import type { GrtpPromise } from '@yyle88/grpt/src/grpcviahttp';
/**
 * Rpcboom service defines methods that return different error types
 * Rpcboom 服务定义返回不同错误类型的方法
 *
 * @generated from protobuf service api.rpcboom.Rpcboom
 */
export interface IRpcboomClient {
    /**
     * BoomUnknown returns UNKNOWN error (500)
     * BoomUnknown 返回 UNKNOWN 错误 (500)
     *
     * @generated from protobuf rpc: BoomUnknown
     */
    boomUnknown(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty>;
    /**
     * BoomNotFound returns USER_NOT_FOUND error (404)
     * BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
     *
     * @generated from protobuf rpc: BoomNotFound
     */
    boomNotFound(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty>;
    /**
     * BoomVague returns GREETER_UNSPECIFIED error (500)
     * BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
     *
     * @generated from protobuf rpc: BoomVague
     */
    boomVague(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty>;
    /**
     * BoomTxError returns TX_ERROR error (500)
     * BoomTxError 返回 TX_ERROR 错误 (500)
     *
     * @generated from protobuf rpc: BoomTxError
     */
    boomTxError(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty>;
    /**
     * BoomDbError returns DB_ERROR error (500)
     * BoomDbError 返回 DB_ERROR 错误 (500)
     *
     * @generated from protobuf rpc: BoomDbError
     */
    boomDbError(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty>;
}
/**
 * Rpcboom service defines methods that return different error types
 * Rpcboom 服务定义返回不同错误类型的方法
 *
 * @generated from protobuf service api.rpcboom.Rpcboom
 */
export class RpcboomClient implements IRpcboomClient, ServiceInfo {
    typeName = Rpcboom.typeName;
    methods = Rpcboom.methods;
    options = Rpcboom.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * BoomUnknown returns UNKNOWN error (500)
     * BoomUnknown 返回 UNKNOWN 错误 (500)
     *
     * @generated from protobuf rpc: BoomUnknown
     */
    boomUnknown(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrtp<Empty, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * BoomNotFound returns USER_NOT_FOUND error (404)
     * BoomNotFound 返回 USER_NOT_FOUND 错误 (404)
     *
     * @generated from protobuf rpc: BoomNotFound
     */
    boomNotFound(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrtp<Empty, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * BoomVague returns GREETER_UNSPECIFIED error (500)
     * BoomVague 返回 GREETER_UNSPECIFIED 错误 (500)
     *
     * @generated from protobuf rpc: BoomVague
     */
    boomVague(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrtp<Empty, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * BoomTxError returns TX_ERROR error (500)
     * BoomTxError 返回 TX_ERROR 错误 (500)
     *
     * @generated from protobuf rpc: BoomTxError
     */
    boomTxError(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrtp<Empty, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * BoomDbError returns DB_ERROR error (500)
     * BoomDbError 返回 DB_ERROR 错误 (500)
     *
     * @generated from protobuf rpc: BoomDbError
     */
    boomDbError(input: Empty, options?: RpcOptions): GrtpPromise<Empty, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return executeGrtp<Empty, Empty>("unary", this._transport, method, opt, input);
    }
}
